version: '3'

services:
  nginx:
    image: nginx:1.19.3-alpine
    restart: always
    working_dir: /app
    volumes:
      - ./:/app/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx/
    ports:
      - ${APP_EXPOSED_PORT:-0}:80
    depends_on:
      - php

  php:
    build: ./docker/php
    image: ${APP_NAME:-app}_php
    working_dir: /app
    volumes:
      - ./:/app/
      - ~/.ssh/:/root/.ssh/
    depends_on:
      - mysql
      - redis

  cron:
    image: ${APP_NAME:-app}_php
    restart: always
    working_dir: /app
    command: /bin/sh -c "/app/docker/php/cron.sh"
    volumes:
      - ./:/app/
    depends_on:
      - php

  worker:
    image: ${APP_NAME:-app}_php
    restart: always
    working_dir: /app
    command: [ "php", "artisan", "-vvv", "queue:work", "redis", "--sleep=1", "--daemon", "--tries=3" ]
    volumes:
      - ./:/app
    depends_on:
      - php

  mysql:
    image: mysql:5.7.32
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-app}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
    ports:
      - 127.0.0.1:${DB_EXPOSED_PORT:-0}:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql

  redis:
    image: redis:6.0.9-alpine3.12
    restart: always
    ports:
      - 127.0.0.1:${REDIS_EXPOSED_PORT:-0}:6379
